/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetexam.dialog;

import javax.swing.JOptionPane;
import projetexam.constructor.Personnel;
import projetexam.manager.PersonnelManager;

/**
 *
 * @author calvindev
 */
public class AjoutPersonel extends javax.swing.JDialog {

    /**
     * Creates new form AjoutPersonel
     */
    public AjoutPersonel(java.awt.Frame parent , boolean modal) {
        super (parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        NomPers = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        PostCombo = new javax.swing.JComboBox<>();
        jLabel68 = new javax.swing.JLabel();
        NumeroPers = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel69 = new javax.swing.JLabel();
        StatutCombo = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel53.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jLabel53.setText("JOUTER UN PERSONNEL");

        jLabel65.setText("NON DU PERSONNEL");

        NomPers.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N

        jLabel67.setText("POSTE");

        PostCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Personnel", "Chaffeur", " " }));

        jLabel68.setText("NUMERO DE TELEPHONE");

        NumeroPers.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N

        jLabel69.setText("STATUT");

        StatutCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "actif", "inactif" }));

        jButton14.setText("ENREGISTRER");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NumeroPers)
                        .addComponent(PostCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NomPers)
                        .addComponent(jLabel69)
                        .addComponent(StatutCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomPers, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PostCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumeroPers, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatutCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Personnel personnelModifie = null; // Ajouter cette variable pour stocker le personnel en cours de modification

    public void setPersonnelInfo(Personnel personnel) {
        if (personnel != null) {
            personnelModifie = personnel;
            NomPers.setText(personnel.getNom());
            PostCombo.setSelectedItem(personnel.getPoste());
            NumeroPers.setText(personnel.getTelephone());
            jButton14.setText("MODIFIER"); // Change le texte du bouton
        }
    }

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            String nom = NomPers.getText().trim();
            String poste = PostCombo.getSelectedItem().toString();
            String numero = NumeroPers.getText().trim();
            String statut = StatutCombo.getSelectedItem().toString();
            
            // Validation des champs
            if(nom.isEmpty() || poste.isEmpty() || numero.isEmpty()){
                JOptionPane.showMessageDialog(null, "Tous les champs sont obligatoires", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validation du nom (pas de caractères spéciaux)
            if (!nom.matches("^[a-zA-ZÀ-ÿ\\s]+$")) {
                JOptionPane.showMessageDialog(null, "Le nom ne doit contenir que des lettres", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validation du numéro de téléphone
            if (!numero.matches("^[0-9]{10}$")) {
                JOptionPane.showMessageDialog(null, "Le numéro de téléphone doit contenir 10 chiffres", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Confirmation avant ajout
            int confirm = JOptionPane.showConfirmDialog(
                this,
                "Êtes-vous sûr de vouloir ajouter ce personnel ?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
            );

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            // Ajout
            Personnel personnel = new Personnel(0, nom, poste, numero, statut);
            boolean success = PersonnelManager.AddPersonnel(personnel);
            if(success){
                JOptionPane.showMessageDialog(null, "Personnel ajouté avec succès !", "Succès", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Une erreur inattendue est survenue : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void reinitialiserFormulaire() {
        NomPers.setText("");
        PostCombo.setSelectedIndex(0);
        NumeroPers.setText("");
        personnelModifie = null;
        jButton14.setText("ENREGISTRER");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutPersonel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               java.awt.Frame parentFrame = new javax.swing.JFrame();
               AjoutPersonel popup = new AjoutPersonel(parentFrame , true);
               popup.setLocationRelativeTo(null);
               popup.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NomPers;
    private javax.swing.JTextField NumeroPers;
    private javax.swing.JComboBox<String> PostCombo;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> StatutCombo;
    private javax.swing.JLabel jLabel69;
    // End of variables declaration//GEN-END:variables
}
